config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  post '/logout' => 'sessions#destroy'
  get '/profile' => 'users#profile'
  post '/profile' => 'users#profile'
  resources :user_book_reviews, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :books, only: [:index, :show]
  resources :authors, only: [:index, :show]
  resources :genres, only: [:index, :show]
  resources :users, only: [:index, :show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
    has_many :genres, through: :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  has_many :user_book_reviews
  has_many :users, through: :user_book_reviews
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books
    has_many :authors, through: :books
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_book_reviews
    has_many :books, through: :user_book_reviews
    has_secure_password

    validates :name, presence: true
    validates :password_digest, presence: true

end

app/models/user_book_review.rb
class UserBookReview < ApplicationRecord
  belongs_to :user
  belongs_to :book

  def user_name=(name)
    self.user = User.find_or_create_by(name: name)
  
  end

  def user_name
    self.user ? self.user.name : nil
  end

  def book_name=(name)
    self.book = Book.find_or_create_by(name: name)
  end

  def book_name
    self.book ? self.book.title : nil
  end

  def time
    self.created_at.to_formatted_s(:long) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :current_user
  
    def current_user
      @user = (User.find_by(id: session[:user_id]) || User.new)
    end
  
    def logged_in?
      current_user.id != nil
    end
  
    def require_logged_in
      return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def index
        @authors = Author.all.sort_by { |hash| hash[:name] }
    end

    def show
        @author = Author.find(params[:id])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all.sort_by { |hash| hash[:title] }
    end

    def show
        @book = Book.find(params[:id])
        @books_author = @book.author
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
    def index
        @genres = Genre.all.sort_by { |hash| hash[:name] }
    end

    def show
        @genre = Genre.find(params[:id])
        @genre_books = @genre.books.sort_by { |hash| hash[:title] }
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logged_in
  skip_before_action :require_logged_in, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(name: params[:user][:name])
    user = user.try(:authenticate, params[:user][:password])
    return redirect_to(controller: 'users', action: 'new') unless user
    session[:user_id] = user.id
    @user = user
    redirect_to profile_path
  end

  def destroy
    session.delete :user_id
    redirect_to '/login'
  end

end

app/controllers/user_book_reviews_controller.rb
class UserBookReviewsController < ApplicationController
    before_action :require_logged_in
    def show
        @userbookreview = UserBookReview.find(params[:id])

    end

    def new
        @userbookreview = UserBookReview.new

    end

    def create
        @userbookreview = UserBookReview.create(userbookreview_params)
        redirect_to profile_path
    end

    def edit
        @userbookreview = UserBookReview.find(params[:id])
    end

    def update
        @userbookreview = UserBookReview.find(params[:id])
        @userbookreview.update(userbookreview_params)
        redirect_to profile_path
    end

    def destroy
        @userbookreview = UserBookReview.find(params[:id])
        @userbookreview.destroy
        redirect_to profile_path
    end

    private

    def userbookreview_params
        params.require(:user_book_review).permit(:review, :rating, :user_id, :book_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_in
    skip_before_action :require_logged_in, only: [:new, :create]

    def index
        @users = User.all.sort_by { |hash| hash[:name] }
    end

    def show
        @user = User.find(params[:id])

    end

    def profile
        
    end

    def new
        @user = User.new

    end

    def create
        @user = User.create(user_params)
        return redirect_to controller: 'users', action: 'new' unless @user.save
        session[:user_id] = @user.id
        redirect_to controller: 'sessions', action: 'new'
    end

    private

    def user_params
        params.require(:user).permit(:name, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_book_reviews_helper.rb
module UserBookReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/index.html.erb
<h1 class="header">Authors</h1><br>

<div class="author">
<ul>
<% @authors.each do |author| %>
    <li><%= link_to author.name, author %></li>
<% end %>
</ul>
</div>

app/views/authors/show.html.erb
<h1 class="header"><%= @author.name %></h1><br>

<div class="author_books">
<h2>Books:</h2><br>

<% @author.books.each do |b| %>
    <h3><%= link_to b.title, b %></h3>
    <h4>Genre: <%= link_to b.genre.name, b.genre %></h4><br>
<% end %>
</div>

app/views/books/index.html.erb
<h1 class="header">Books</h1><br>

<div class="book">
<ul>
    <% @books.each do |book| %>
        <li><%= link_to book.title, book %></li>
    <% end %>
</ul>
</div>

app/views/books/show.html.erb
<h1 class="header"><%= @book.title %></h1>
<h2 id="by">by <%= link_to @book.author.name, @books_author %></h2><br>

<div id="by">
    <%= button_to "Write a review", new_user_book_review_path, method: :get %>
    </div><br>

<h3>Reviews:</h3>

<% if @book.user_book_reviews.empty? %>
    <p>There's nothing here, be the first to review!</p>
<% else %>
<div class="review">
    <% @book.user_book_reviews.each do |u| %>
    <div>
        <p id="time"><%= u.time %></p><br>
        <h4>Reviewed by: <%= link_to u.user.name.capitalize, u.user %></h4>
        <p><%= u.review %></p>
        <p id="rating">Rating: <%= u.rating %></p><br>
    </div>
    <% end %>
</div>
<% end %>

app/views/genres/index.html.erb
<h1 class="header">Genres</h1><br>

<div class="genre">
<ul>
<% @genres.each do |genre| %>
    <li><%= link_to genre.name, genre %></li>
<% end %>
</ul>
</div>

app/views/genres/show.html.erb
<h1 class="header"><%= @genre.name %> Books</h1><br>

<div class="genre_books">
<ul>
    <% @genre_books.each do |b| %>
        <p><%= link_to b.title, b %></p>
    <% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://unpkg.com/bulmaswatch/sandstone/bulmaswatch.min.css">
  </head>

  <div class = navbar>
    <div><%= link_to "📚 My Profile", profile_path %></div>
    <div><%= link_to "Authors", authors_path %></div>
    <div><%= link_to "Genres", genres_path %></div>
    <div><%= link_to "Books", books_path %></div>
    <div><%= link_to "Bookshelves", users_path %></div>
    <div><%= link_to "Create a Review", new_user_book_review_path %></div>
  </div>

  <body class="body">
 
  </body>
    <main class="main">
  
     <%= yield %>

    </main>
  
</html>

app/views/user_book_reviews/_form.html.erb
<div class="form">

    <%= form_for @userbookreview do |f| %>

       <%= f.hidden_field :user_id, value: session[:user_id]%>
    <p><%= f.label :book %></p>
    <p><%= f.collection_select :book_id, Book.all, :id, :title %></p><br>

    <p><%= f.label :review %></p>
    <p><%= f.text_area :review %></p><br>

    <p><%= f.label :rating %></p>
    <p><%= f.select :rating, (1..10) %></p><br>

    <p><%= f.submit "Submit Review" %></p>
    <% end %>
</div>

app/views/user_book_reviews/edit.html.erb
<h1 class="header">Update Book Review Form</h1>

<p id="by">Edit this book review on your bookshelf!</p><br>

<%= render "form" %>

<br><p><%= button_to "Delete This Review", @userbookreview, method: :delete %></p>

app/views/user_book_reviews/new.html.erb
<h1 class="header">Book Review Form</h1>
<p id="by">Add a book review to your bookshelf!</p><br>

<%= render "form" %>

app/views/users/index.html.erb
<h1 class="header">Bookshelves</h1><br>
<p>Check out other Reviewer's bookshelves:</p><br>

<div class="user">
<ul>
<% @users.each do |user| %>
    <li><%= link_to user.name, user %></li>
<% end %>
</ul>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div><%= form_for @user do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name  %></p>
<p><%= f.label :password %></p>
<p><%= f.password_field :password %></p>
<p><%= f.label :password_confirmation %></p>
<p><%= f.password_field :password_confirmation %></p>
<p><%= f.submit "New User" %></p>
<% end %></div>

app/views/users/profile.html.erb
<h1 class="header">Hi, <%= @user.name.capitalize %></h1>
<h2 id="by"><%= button_to "Logout", logout_path, method: :get %> </h2><br>
<div id="by">
    <%= button_to "Write a review", new_user_book_review_path, method: :get %>
</div>

<% @user.user_book_reviews.each do |u| %>
<div class="profile">
    
    <p id="time"><%= u.time %></p><br>
    <h2 id="profile_book"><%= link_to u.book_name, book_path(u.book_id) %></h2>
    <p id="author">Author: <%= link_to u.book.author.name, author_path(u.book.author_id) %></p>
    <p id="genre">Genre: <%= link_to u.book.genre.name, genre_path(u.book.genre_id) %></p>
    <p id="review">Review: <div id=review_text><%= u.review %></div></p>
    <p id="rating">Rating: <div id=review_rating><%= u.rating  %></div></p>
    <p id="edit_link"><%= button_to "Edit form", edit_user_book_review_path(u.id), method: :get %></p><br>
    
</div>
<% end %>

app/views/users/show.html.erb
<h1 class="header"><%= @user.name %>'s Bookshelf</h1><br>

<% @user.user_book_reviews.each do |u| %>
    <div class="profile">

    <p id="time"><%= u.time %></p><br>
    <h2 id="profile_book"><%= link_to u.book_name, book_path(u.book_id) %></h2>
    <p id="author">Author: <%= link_to u.book.author.name, author_path(u.book.author_id) %></p>
    <p id="genre">Genre: <%= link_to u.book.genre.name, genre_path(u.book.genre_id) %></p>
    <p id="review">Review: <div id=review_text><%= u.review %></div></p>
    <p id="rating">Rating: <div id=review_rating><%= u.rating  %></div></p>
 
</div>
    <% end %>
